In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
emissions_data_batched = pd.read_csv('emissions_batched_benchmakrs.csv')
emissions_data_nonbatched = pd.read_csv('emissions_benchmakrs.csv')

In [3]:
emissions_data_batched.head(5)

,timestamp,project_name,run_id,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,...,cpu_count,cpu_model,gpu_count,gpu_model,longitude,latitude,ram_total_size,tracking_mode,on_cloud,pue
0,2024-08-13T10:18:36,llama3_1_8b-arena-hard-v0.1-4gpus-run_1,a29058ee-62ad-4d69-bfe1-3eb13e10372d,397.887474,0.029054,0.000073,42.5,287.699319,68.162162,0.005731,...,48,AMD EPYC 7R13 Processor,4,4 x NVIDIA L4,-83.0061,39.9625,181.765766,machine,N,1.22
1,2024-08-13T10:25:54,llama3_1_8b-arena-hard-v0.1-4gpus-run_2,a1f46fd3-1e50-42f2-94b5-49016e012a86,424.195516,0.032371,0.000076,42.5,287.760744,68.162162,0.006110,...,48,AMD EPYC 7R13 Processor,4,4 x NVIDIA L4,-83.0061,39.9625,181.765766,machine,N,1.22
2,2024-08-13T10:33:21,llama3_1_8b-arena-hard-v0.1-4gpus-run_3,084245c7-74ca-4706-aae5-3d411eef3567,431.738808,0.033038,0.000077,42.5,285.797297,68.162162,0.006218,...,48,AMD EPYC 7R13 Processor,4,4 x NVIDIA L4,-83.0061,39.9625,181.765766,machine,N,1.22
3,2024-08-13T10:40:26,llama3_1_8b-arena-hard-v0.1-4gpus-run_4,52cca1da-8845-42b0-a78c-923668c3a2ea,409.483063,0.031534,0.000077,42.5,287.372991,68.162162,0.005898,...,48,AMD EPYC 7R13 Processor,4,4 x NVIDIA L4,-83.0061,39.9625,181.765766,machine,N,1.22
4,2024-08-13T10:47:25,llama3_1_8b-arena-hard-v0.1-4gpus-run_5,b3224b99-b7a8-425e-9733-f201dcb9336c,404.363748,0.031162,0.000077,42.5,286.115885,68.162162,0.005824,...,48,AMD EPYC 7R13 Processor,4,4 x NVIDIA L4,-83.0061,39.9625,181.765766,machine,N,1.22

In [4]:
# Strip "-run_x" and "-xgpus" and "-arena-hard-v0.1" from the project_name and create a new column for model_name
emissions_data_batched['model_name'] = emissions_data_batched['project_name'].apply(lambda x: re.sub(r'-run_\d+', '', re.sub(r'-arena-hard-v0.1', '', x)))

In [5]:
emissions_data_batched.head(5)

,timestamp,project_name,run_id,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,...,cpu_model,gpu_count,gpu_model,longitude,latitude,ram_total_size,tracking_mode,on_cloud,pue,model_name
0,2024-08-13T10:18:36,llama3_1_8b-arena-hard-v0.1-4gpus-run_1,a29058ee-62ad-4d69-bfe1-3eb13e10372d,397.887474,0.029054,0.000073,42.5,287.699319,68.162162,0.005731,...,AMD EPYC 7R13 Processor,4,4 x NVIDIA L4,-83.0061,39.9625,181.765766,machine,N,1.22,llama3_1_8b-4gpus
1,2024-08-13T10:25:54,llama3_1_8b-arena-hard-v0.1-4gpus-run_2,a1f46fd3-1e50-42f2-94b5-49016e012a86,424.195516,0.032371,0.000076,42.5,287.760744,68.162162,0.006110,...,AMD EPYC 7R13 Processor,4,4 x NVIDIA L4,-83.0061,39.9625,181.765766,machine,N,1.22,llama3_1_8b-4gpus
2,2024-08-13T10:33:21,llama3_1_8b-arena-hard-v0.1-4gpus-run_3,084245c7-74ca-4706-aae5-3d411eef3567,431.738808,0.033038,0.000077,42.5,285.797297,68.162162,0.006218,...,AMD EPYC 7R13 Processor,4,4 x NVIDIA L4,-83.0061,39.9625,181.765766,machine,N,1.22,llama3_1_8b-4gpus
3,2024-08-13T10:40:26,llama3_1_8b-arena-hard-v0.1-4gpus-run_4,52cca1da-8845-42b0-a78c-923668c3a2ea,409.483063,0.031534,0.000077,42.5,287.372991,68.162162,0.005898,...,AMD EPYC 7R13 Processor,4,4 x NVIDIA L4,-83.0061,39.9625,181.765766,machine,N,1.22,llama3_1_8b-4gpus
4,2024-08-13T10:47:25,llama3_1_8b-arena-hard-v0.1-4gpus-run_5,b3224b99-b7a8-425e-9733-f201dcb9336c,404.363748,0.031162,0.000077,42.5,286.115885,68.162162,0.005824,...,AMD EPYC 7R13 Processor,4,4 x NVIDIA L4,-83.0061,39.9625,181.765766,machine,N,1.22,llama3_1_8b-4gpus

In [6]:
emissions_data_nonbatched['model_name'] = emissions_data_nonbatched['project_name'].apply(lambda x: re.sub(r'-arena-hard-v0.1', '', x))

In [7]:
emissions_data_nonbatched.head(5)

,timestamp,project_name,run_id,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,...,cpu_model,gpu_count,gpu_model,longitude,latitude,ram_total_size,tracking_mode,on_cloud,pue,model_name
0,2024-08-05T11:52:32,llama3_1_70b-arena-hard-v0.1-8gpus,845ed7f7-e6df-420b-b0f6-74c463c5f85a,1867.868346,0.347547,0.000186,42.5,577.583519,273.079635,0.026902,...,AMD EPYC 7R13 Processor,8,8 x NVIDIA L4,-83.0061,39.9625,728.212360,machine,N,1.22,llama3_1_70b-8gpus
1,2024-08-05T15:43:54,llama3_1_70b_fp8-arena-hard-v0.1-8gpus,5a3b3a9b-6d73-46b0-8b43-64a71ded0999,863.529238,0.138361,0.000160,42.5,576.523141,273.079624,0.012437,...,AMD EPYC 7R13 Processor,8,8 x NVIDIA L4,-83.0061,39.9625,728.212330,machine,N,1.22,llama3_1_70b_fp8-8gpus
2,2024-08-06T08:09:33,llama3_1_70b_awq_int4-arena-hard-v0.1-8gpus,c92fea3c-ce86-4c7e-8731-c7cd7fb5f115,913.961446,0.150479,0.000165,42.5,577.146518,273.079618,0.013164,...,AMD EPYC 7R13 Processor,8,8 x NVIDIA L4,-83.0061,39.9625,728.212315,machine,N,1.22,llama3_1_70b_awq_int4-8gpus
3,2024-08-06T09:04:39,llama3_1_70b_awq_int4-arena-hard-v0.1-8gpus,895031ee-302e-47d7-99c1-e8e383876f8f,823.504677,0.132878,0.000161,42.5,562.538170,273.079618,0.011861,...,AMD EPYC 7R13 Processor,8,8 x NVIDIA L4,-83.0061,39.9625,728.212315,machine,N,1.22,llama3_1_70b_awq_int4-8gpus
4,2024-08-06T09:45:22,llama3_1_70b_fp8-arena-hard-v0.1-8gpus,7c43c183-1897-41d5-ad9f-2d2c9711cf4e,904.004853,0.148404,0.000164,42.5,580.996490,273.079618,0.013020,...,AMD EPYC 7R13 Processor,8,8 x NVIDIA L4,-83.0061,39.9625,728.212315,machine,N,1.22,llama3_1_70b_fp8-8gpus

In [8]:
# Group by the new model_name and calculate the mean for the selected columns
df_batched = emissions_data_batched.groupby('model_name').agg({
    'duration': 'mean',
    'emissions': 'mean',
    'emissions_rate': 'mean',
    'cpu_power': 'mean',
    'gpu_power': 'mean',
    'ram_power': 'mean',
    'cpu_energy': 'mean',
    'gpu_energy': 'mean',
    'ram_energy': 'mean',
    'energy_consumed': 'mean',
    'gpu_count': 'first'}).reset_index()
    
df_nonbatched = emissions_data_nonbatched.groupby('model_name').agg({
    'duration': 'mean',
    'emissions': 'mean',
    'emissions_rate': 'mean',
    'cpu_power': 'mean',
    'gpu_power': 'mean',
    'ram_power': 'mean',
    'cpu_energy': 'mean',
    'gpu_energy': 'mean',
    'ram_energy': 'mean',
    'energy_consumed': 'mean',
    'gpu_count': 'first'}).reset_index()

In [9]:
df_batched.head(5)

,model_name,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,gpu_energy,ram_energy,energy_consumed,gpu_count
0,llama3_1_8b-4gpus,406.711346,0.031154,0.000077,42.5,290.192641,68.162162,0.005858,0.031608,0.009385,0.046852,4
1,llama3_1_8b_fp8-4gpus,341.294352,0.025867,0.000076,42.5,275.763867,68.162159,0.004916,0.026110,0.007876,0.038901,4
2,llama3_1_8b_guided-4gpus,669.515852,0.053497,0.000080,42.5,290.152320,68.162162,0.009643,0.055361,0.015449,0.080452,4
3,llama3_8b-4gpus,283.092776,0.021880,0.000077,42.5,288.211588,68.162159,0.004077,0.022296,0.006532,0.032905,4
4,llama3_8b_guided-4gpus,529.400023,0.042992,0.000081,42.5,288.900793,68.162159,0.007625,0.044814,0.012216,0.064655,4

In [10]:
df_nonbatched.head(5)

,model_name,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,gpu_energy,ram_energy,energy_consumed,gpu_count
0,llama3_1_70b-8gpus,2513.262675,0.471343,0.000187,42.5,563.751591,273.079628,0.036198,0.440552,0.232091,0.708841,8
1,llama3_1_70b_awq_int4-4gpus,828.743464,0.070360,0.000085,42.5,289.168718,68.162164,0.011936,0.074753,0.019123,0.105812,4
2,llama3_1_70b_awq_int4-8gpus,890.192632,0.146427,0.000164,42.5,573.461085,273.079615,0.012821,0.125151,0.082235,0.220208,8
3,llama3_1_70b_awq_int4-8gpus-guided,1692.569733,0.281111,0.000166,42.5,575.850005,273.079634,0.024378,0.242026,0.156352,0.422756,8
4,llama3_1_70b_fp8-4gpus,1466.116555,0.129593,0.000088,42.5,288.045262,68.162164,0.021116,0.139951,0.033825,0.194892,4

In [11]:
df = pd.concat([df_batched, df_nonbatched], ignore_index=True)
df.head(10)

,model_name,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,gpu_energy,ram_energy,energy_consumed,gpu_count
0,llama3_1_8b-4gpus,406.711346,0.031154,0.000077,42.5,290.192641,68.162162,0.005858,0.031608,0.009385,0.046852,4
1,llama3_1_8b_fp8-4gpus,341.294352,0.025867,0.000076,42.5,275.763867,68.162159,0.004916,0.026110,0.007876,0.038901,4
2,llama3_1_8b_guided-4gpus,669.515852,0.053497,0.000080,42.5,290.152320,68.162162,0.009643,0.055361,0.015449,0.080452,4
3,llama3_8b-4gpus,283.092776,0.021880,0.000077,42.5,288.211588,68.162159,0.004077,0.022296,0.006532,0.032905,4
4,llama3_8b_guided-4gpus,529.400023,0.042992,0.000081,42.5,288.900793,68.162159,0.007625,0.044814,0.012216,0.064655,4
5,mistral_nemo-4gpus,453.990921,0.037947,0.000084,42.5,288.566338,68.162164,0.006539,0.040054,0.010475,0.057068,4
6,mistral_nemo_fp8-4gpus,352.530645,0.027009,0.000077,42.5,285.410582,68.162164,0.005077,0.027405,0.008135,0.040618,4
7,mistral_nemo_fp8_guided-4gpus,712.147651,0.055511,0.000078,42.5,329.127108,68.162164,0.010257,0.056792,0.016433,0.083482,4
8,mistral_nemo_guided-4gpus,684.076005,0.057035,0.000083,42.5,288.828071,68.162164,0.009853,0.060137,0.015784,0.085773,4
9,llama3_1_70b-8gpus,2513.262675,0.471343,0.000187,42.5,563.751591,273.079628,0.036198,0.440552,0.232091,0.708841,8

In [12]:
df['model_name'] = df['model_name'].apply(lambda x: re.sub(r'-\d+gpus', '', x))

In [13]:
df.head(5)

,model_name,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,gpu_energy,ram_energy,energy_consumed,gpu_count
0,llama3_1_8b,406.711346,0.031154,0.000077,42.5,290.192641,68.162162,0.005858,0.031608,0.009385,0.046852,4
1,llama3_1_8b_fp8,341.294352,0.025867,0.000076,42.5,275.763867,68.162159,0.004916,0.026110,0.007876,0.038901,4
2,llama3_1_8b_guided,669.515852,0.053497,0.000080,42.5,290.152320,68.162162,0.009643,0.055361,0.015449,0.080452,4
3,llama3_8b,283.092776,0.021880,0.000077,42.5,288.211588,68.162159,0.004077,0.022296,0.006532,0.032905,4
4,llama3_8b_guided,529.400023,0.042992,0.000081,42.5,288.900793,68.162159,0.007625,0.044814,0.012216,0.064655,4

In [14]:
# Create the guided column
df['guided'] = df['model_name'].apply(lambda x: 1 if '_guided' in x else 0)

# Strip "_guided" from the model name
df['model_name'] = df['model_name'].apply(lambda x: re.sub(r'_guided', '', x))

In [15]:
df.head(5)

,model_name,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,gpu_energy,ram_energy,energy_consumed,gpu_count,guided
0,llama3_1_8b,406.711346,0.031154,0.000077,42.5,290.192641,68.162162,0.005858,0.031608,0.009385,0.046852,4,0
1,llama3_1_8b_fp8,341.294352,0.025867,0.000076,42.5,275.763867,68.162159,0.004916,0.026110,0.007876,0.038901,4,0
2,llama3_1_8b,669.515852,0.053497,0.000080,42.5,290.152320,68.162162,0.009643,0.055361,0.015449,0.080452,4,1
3,llama3_8b,283.092776,0.021880,0.000077,42.5,288.211588,68.162159,0.004077,0.022296,0.006532,0.032905,4,0
4,llama3_8b,529.400023,0.042992,0.000081,42.5,288.900793,68.162159,0.007625,0.044814,0.012216,0.064655,4,1

In [16]:
# Add a new column 'quantization' based on the suffixes in the model name
def assign_quantization(model_name):
    if '_fp8' in model_name:
        return 'fp8'
    elif '_awq_int4' in model_name:
        return 'awq_int4'
    else:
        return 'bf16'

In [17]:
df['quantization'] = df['model_name'].apply(assign_quantization)

# Strip the quantization suffixes from the model name
df['model_name'] = df['model_name'].apply(lambda x: re.sub(r'_fp8|_awq_int4', '', x))

In [18]:
df.head(10)

,model_name,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,gpu_energy,ram_energy,energy_consumed,gpu_count,guided,quantization
0,llama3_1_8b,406.711346,0.031154,0.000077,42.5,290.192641,68.162162,0.005858,0.031608,0.009385,0.046852,4,0,bf16
1,llama3_1_8b,341.294352,0.025867,0.000076,42.5,275.763867,68.162159,0.004916,0.026110,0.007876,0.038901,4,0,fp8
2,llama3_1_8b,669.515852,0.053497,0.000080,42.5,290.152320,68.162162,0.009643,0.055361,0.015449,0.080452,4,1,bf16
3,llama3_8b,283.092776,0.021880,0.000077,42.5,288.211588,68.162159,0.004077,0.022296,0.006532,0.032905,4,0,bf16
4,llama3_8b,529.400023,0.042992,0.000081,42.5,288.900793,68.162159,0.007625,0.044814,0.012216,0.064655,4,1,bf16
5,mistral_nemo,453.990921,0.037947,0.000084,42.5,288.566338,68.162164,0.006539,0.040054,0.010475,0.057068,4,0,bf16
6,mistral_nemo,352.530645,0.027009,0.000077,42.5,285.410582,68.162164,0.005077,0.027405,0.008135,0.040618,4,0,fp8
7,mistral_nemo,712.147651,0.055511,0.000078,42.5,329.127108,68.162164,0.010257,0.056792,0.016433,0.083482,4,1,fp8
8,mistral_nemo,684.076005,0.057035,0.000083,42.5,288.828071,68.162164,0.009853,0.060137,0.015784,0.085773,4,1,bf16
9,llama3_1_70b,2513.262675,0.471343,0.000187,42.5,563.751591,273.079628,0.036198,0.440552,0.232091,0.708841,8,0,bf16

In [19]:
# Function to extract model class and remove the suffix from the model name
def extract_param_size(model_name):
    match = re.search(r'_\d+b', model_name)
    if match:
        param_size = match.group(0).lstrip('_')
        param_size = param_size.rstrip('b')
        return param_size
    return ''

In [20]:
df['param_size'] = df['model_name'].apply(extract_param_size)
df['model_class'] = df['model_name'].apply(lambda x: re.sub(r'_\d+b', '', x))

df.head(20)

,model_name,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,gpu_energy,ram_energy,energy_consumed,gpu_count,guided,quantization,param_size,model_class
0,llama3_1_8b,406.711346,0.031154,0.000077,42.5,290.192641,68.162162,0.005858,0.031608,0.009385,0.046852,4,0,bf16,8,llama3_1
1,llama3_1_8b,341.294352,0.025867,0.000076,42.5,275.763867,68.162159,0.004916,0.026110,0.007876,0.038901,4,0,fp8,8,llama3_1
2,llama3_1_8b,669.515852,0.053497,0.000080,42.5,290.152320,68.162162,0.009643,0.055361,0.015449,0.080452,4,1,bf16,8,llama3_1
3,llama3_8b,283.092776,0.021880,0.000077,42.5,288.211588,68.162159,0.004077,0.022296,0.006532,0.032905,4,0,bf16,8,llama3
4,llama3_8b,529.400023,0.042992,0.000081,42.5,288.900793,68.162159,0.007625,0.044814,0.012216,0.064655,4,1,bf16,8,llama3
5,mistral_nemo,453.990921,0.037947,0.000084,42.5,288.566338,68.162164,0.006539,0.040054,0.010475,0.057068,4,0,bf16,,mistral_nemo
6,mistral_nemo,352.530645,0.027009,0.000077,42.5,285.410582,68.162164,0.005077,0.027405,0.008135,0.040618,4,0,fp8,,mistral_nemo
7,mistral_nemo,712.147651,0.055511,0.000078,42.5,329.127108,68.162164,0.010257,0.056792,0.016433,0.083482,4,1,fp8,,mistral_nemo
8,mistral_nemo,684.076005,0.057035,0.000083,42.5,288.828071,68.162164,0.009853,0.060137,0.015784,0.085773,4,1,bf16,,mistral_nemo
9,llama3_1_70b,2513.262675,0.471343,0.000187,42.5,563.751591,273.079628,0.036198,0.440552,0.232091,0.708841,8,0,bf16,70,llama3_1
10,llama3_1_70b,828.743464,0.070360,0.000085,42.5,289.168718,68.162164,0.011936,0.074753,0.019123,0.105812,4,0,awq_int4,70,llama3_1
11,llama3_1_70b,890.192632,0.146427,0.000164,42.5,573.461085,273.079615,0.012821,0.125151,0.082235,0.220208,8,0,awq_int4,70,llama3_1
12,llama3_1_70b-guided,1692.569733,0.281111,0.000166,42.5,575.850005,273.079634,0.024378,0.242026,0.156352,0.422756,8,0,awq_int4,70,llama3_1-guided
13,llama3_1_70b,1466.116555,0.129593,0.000088,42.5,288.045262,68.162164,0.021116,0.139951,0.033825,0.194892,4,0,fp8,70,llama3_1
14,llama3_1_70b,885.817376,0.144548,0.000163,42.5,578.474737,273.079617,0.012758,0.122804,0.081821,0.217383,8,0,fp8,70,llama3_1
15,llama3_1_70b-guided,1584.539132,0.254703,0.000161,42.5,579.233452,273.079634,0.022822,0.213861,0.146358,0.383042,8,0,fp8,70,llama3_1-guided
16,llama3_70b,1519.788450,0.283470,0.000187,42.5,576.760477,273.079609,0.021889,0.264062,0.140352,0.426303,8,0,bf16,70,llama3
17,llama3_70b-guided,2963.909088,0.554097,0.000187,42.5,578.761208,273.079634,0.042688,0.516876,0.273729,0.833293,8,0,bf16,70,llama3-guided
18,llama3_70b,811.387838,0.132349,0.000163,42.5,592.132110,273.079609,0.011686,0.112394,0.074956,0.199036,8,0,awq_int4,70,llama3
19,llama3_70b,871.537337,0.143975,0.000165,42.5,575.377740,273.079609,0.012553,0.123465,0.080503,0.216521,8,0,fp8,70,llama3

In [22]:
df['duration_minutes'] = df['duration'] / 60
df.head(5)

,model_name,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,gpu_energy,ram_energy,energy_consumed,gpu_count,guided,quantization,param_size,model_class,duration_minutes
0,llama3_1_8b,406.711346,0.031154,0.000077,42.5,290.192641,68.162162,0.005858,0.031608,0.009385,0.046852,4,0,bf16,8,llama3_1,6.778522
1,llama3_1_8b,341.294352,0.025867,0.000076,42.5,275.763867,68.162159,0.004916,0.026110,0.007876,0.038901,4,0,fp8,8,llama3_1,5.688239
2,llama3_1_8b,669.515852,0.053497,0.000080,42.5,290.152320,68.162162,0.009643,0.055361,0.015449,0.080452,4,1,bf16,8,llama3_1,11.158598
3,llama3_8b,283.092776,0.021880,0.000077,42.5,288.211588,68.162159,0.004077,0.022296,0.006532,0.032905,4,0,bf16,8,llama3,4.718213
4,llama3_8b,529.400023,0.042992,0.000081,42.5,288.900793,68.162159,0.007625,0.044814,0.012216,0.064655,4,1,bf16,8,llama3,8.823334