In [34]:
import pandas as pd
import numpy as np
import re
import json

In [35]:
emissions_data_batched = pd.read_csv('emissions_batched_benchmakrs.csv')
emissions_data_nonbatched = pd.read_csv('emissions_benchmakrs.csv')

leaderboard_path = 'arena-hard-auto/leaderboard/arena_hard_leaderboard_20240817.csv'
leaderboard_df = pd.read_csv(leaderboard_path)

In [36]:
# Clean the leaderboard DataFrame
# Extract CI values from the CI column and add them as new columns
leaderboard_df['CI_lower'] = leaderboard_df['CI'].apply(lambda x: float(x.split(',')[0].strip('("(').strip()))
leaderboard_df['CI_upper'] = leaderboard_df['CI'].apply(lambda x: float(x.split(',')[1].strip(')+"').strip()))

# Rename columns to avoid conflicts
leaderboard_df = leaderboard_df.rename(columns={
    'model': 'model_name',
    'avg_tokens': 'output_tok',
    'score': 'arena_score',
    'rating_q025': '95_conf_minus',
    'rating_q975': '95_conf_plus'
})

In [37]:
leaderboard_df

,model_name,arena_score,95_conf_minus,95_conf_plus,CI,output_tok,date,CI_lower,CI_upper
0,gpt-4o,88.09,86.60,89.44,"(-1.49, +1.35)",696.0,2024-08-17,-1.49,1.35
1,gpt-4o-2024-08-06_guided,87.75,86.27,89.18,"(-1.48, +1.43)",625.0,2024-08-17,-1.48,1.43
2,gpt-4o-2024-08-06,86.55,85.08,88.10,"(-1.47, +1.55)",616.0,2024-08-17,-1.47,1.55
3,gpt-4o-mini_guided,86.27,84.67,87.86,"(-1.60, +1.59)",678.0,2024-08-17,-1.60,1.59
4,mistral_large_2_guided,83.63,81.89,85.41,"(-1.74, +1.78)",777.0,2024-08-17,-1.74,1.78
5,mistral_large_2,80.96,78.94,82.60,"(-2.02, +1.64)",684.0,2024-08-17,-2.02,1.64
6,gpt-4o-mini,80.09,78.17,81.92,"(-1.92, +1.83)",631.0,2024-08-17,-1.92,1.83
7,llama3_1_405b_guided,79.47,77.49,81.40,"(-1.98, +1.93)",649.0,2024-08-17,-1.98,1.93
8,llama3_1_70b_guided,78.29,76.17,80.12,"(-2.12, +1.83)",646.0,2024-08-17,-2.12,1.83
9,llama3_1_70b_fp8_guided,75.14,72.89,77.38,"(-2.25, +2.24)",646.0,2024-08-17,-2.25,2.24
10,llama3_1_70b_awq_int4_guided,74.17,72.09,76.32,"(-2.08, +2.15)",640.0,2024-08-17,-2.08,2.15
11,llama3_70b_guided,72.34,70.35,74.53,"(-1.99, +2.19)",583.0,2024-08-17,-1.99,2.19
12,llama3_1_405b,72.20,69.91,73.99,"(-2.29, +1.79)",662.0,2024-08-17,-2.29,1.79
13,mistral_nemo_fp8_guided,70.01,67.74,72.25,"(-2.27, +2.24)",633.0,2024-08-17,-2.27,2.24
14,mistral_nemo_guided,69.60,67.23,71.57,"(-2.37, +1.97)",613.0,2024-08-17,-2.37,1.97
15,llama3_1_70b_fp8,68.79,66.35,71.23,"(-2.44, +2.44)",689.0,2024-08-17,-2.44,2.44
16,llama3_1_70b,68.05,65.91,70.15,"(-2.14, +2.10)",681.0,2024-08-17,-2.14,2.10
17,llama3_1_70b_awq_int4,63.82,61.24,66.03,"(-2.58, +2.21)",641.0,2024-08-17,-2.58,2.21
18,llama3_1_8b_guided,60.90,58.37,63.35,"(-2.53, +2.45)",719.0,2024-08-17,-2.53,2.45
19,llama3_70b_fp8,59.59,57.19,61.86,"(-2.40, +2.27)",614.0,2024-08-17,-2.40,2.27
20,gpt-4-0314,50.00,50.00,50.00,"(-0.00, +0.00)",423.0,2024-08-17,-0.00,0.00
21,mistral_nemo,44.90,42.34,47.46,"(-2.56, +2.56)",541.0,2024-08-17,-2.56,2.56
22,mistral_nemo_fp8,42.73,40.06,45.36,"(-2.67, +2.63)",552.0,2024-08-17,-2.67,2.63
23,llama3_1_8b,26.59,24.63,28.83,"(-1.96, +2.24)",853.0,2024-08-17,-1.96,2.24

In [38]:
input_tok_map = {
    'llama3_1': 135.142,
    'llama3': 135.142,
    'mistral_nemo': 143.19,
}

input_tok_map_guided = {
    'llama3_1': 874.592,
    'llama3': 874.592,
    'mistral_nemo': 921.216,
}

In [39]:
emissions_data_batched.head(5)

,timestamp,project_name,run_id,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,...,cpu_count,cpu_model,gpu_count,gpu_model,longitude,latitude,ram_total_size,tracking_mode,on_cloud,pue
0,2024-08-13T10:18:36,llama3_1_8b-arena-hard-v0.1-4gpus-run_1,a29058ee-62ad-4d69-bfe1-3eb13e10372d,397.887474,0.029054,0.000073,42.5,287.699319,68.162162,0.005731,...,48,AMD EPYC 7R13 Processor,4,4 x NVIDIA L4,-83.0061,39.9625,181.765766,machine,N,1.22
1,2024-08-13T10:25:54,llama3_1_8b-arena-hard-v0.1-4gpus-run_2,a1f46fd3-1e50-42f2-94b5-49016e012a86,424.195516,0.032371,0.000076,42.5,287.760744,68.162162,0.006110,...,48,AMD EPYC 7R13 Processor,4,4 x NVIDIA L4,-83.0061,39.9625,181.765766,machine,N,1.22
2,2024-08-13T10:33:21,llama3_1_8b-arena-hard-v0.1-4gpus-run_3,084245c7-74ca-4706-aae5-3d411eef3567,431.738808,0.033038,0.000077,42.5,285.797297,68.162162,0.006218,...,48,AMD EPYC 7R13 Processor,4,4 x NVIDIA L4,-83.0061,39.9625,181.765766,machine,N,1.22
3,2024-08-13T10:40:26,llama3_1_8b-arena-hard-v0.1-4gpus-run_4,52cca1da-8845-42b0-a78c-923668c3a2ea,409.483063,0.031534,0.000077,42.5,287.372991,68.162162,0.005898,...,48,AMD EPYC 7R13 Processor,4,4 x NVIDIA L4,-83.0061,39.9625,181.765766,machine,N,1.22
4,2024-08-13T10:47:25,llama3_1_8b-arena-hard-v0.1-4gpus-run_5,b3224b99-b7a8-425e-9733-f201dcb9336c,404.363748,0.031162,0.000077,42.5,286.115885,68.162162,0.005824,...,48,AMD EPYC 7R13 Processor,4,4 x NVIDIA L4,-83.0061,39.9625,181.765766,machine,N,1.22

In [40]:
# Strip "-run_x" and "-xgpus" and "-arena-hard-v0.1" from the project_name and create a new column for model_name
emissions_data_batched['model_name'] = emissions_data_batched['project_name'].apply(lambda x: re.sub(r'-run_\d+', '', re.sub(r'-arena-hard-v0.1', '', x)))

In [41]:
emissions_data_batched.head(5)

,timestamp,project_name,run_id,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,...,cpu_model,gpu_count,gpu_model,longitude,latitude,ram_total_size,tracking_mode,on_cloud,pue,model_name
0,2024-08-13T10:18:36,llama3_1_8b-arena-hard-v0.1-4gpus-run_1,a29058ee-62ad-4d69-bfe1-3eb13e10372d,397.887474,0.029054,0.000073,42.5,287.699319,68.162162,0.005731,...,AMD EPYC 7R13 Processor,4,4 x NVIDIA L4,-83.0061,39.9625,181.765766,machine,N,1.22,llama3_1_8b-4gpus
1,2024-08-13T10:25:54,llama3_1_8b-arena-hard-v0.1-4gpus-run_2,a1f46fd3-1e50-42f2-94b5-49016e012a86,424.195516,0.032371,0.000076,42.5,287.760744,68.162162,0.006110,...,AMD EPYC 7R13 Processor,4,4 x NVIDIA L4,-83.0061,39.9625,181.765766,machine,N,1.22,llama3_1_8b-4gpus
2,2024-08-13T10:33:21,llama3_1_8b-arena-hard-v0.1-4gpus-run_3,084245c7-74ca-4706-aae5-3d411eef3567,431.738808,0.033038,0.000077,42.5,285.797297,68.162162,0.006218,...,AMD EPYC 7R13 Processor,4,4 x NVIDIA L4,-83.0061,39.9625,181.765766,machine,N,1.22,llama3_1_8b-4gpus
3,2024-08-13T10:40:26,llama3_1_8b-arena-hard-v0.1-4gpus-run_4,52cca1da-8845-42b0-a78c-923668c3a2ea,409.483063,0.031534,0.000077,42.5,287.372991,68.162162,0.005898,...,AMD EPYC 7R13 Processor,4,4 x NVIDIA L4,-83.0061,39.9625,181.765766,machine,N,1.22,llama3_1_8b-4gpus
4,2024-08-13T10:47:25,llama3_1_8b-arena-hard-v0.1-4gpus-run_5,b3224b99-b7a8-425e-9733-f201dcb9336c,404.363748,0.031162,0.000077,42.5,286.115885,68.162162,0.005824,...,AMD EPYC 7R13 Processor,4,4 x NVIDIA L4,-83.0061,39.9625,181.765766,machine,N,1.22,llama3_1_8b-4gpus

In [42]:
emissions_data_nonbatched['model_name'] = emissions_data_nonbatched['project_name'].apply(lambda x: re.sub(r'-arena-hard-v0.1', '', x))

In [43]:
emissions_data_nonbatched.head(5)

,timestamp,project_name,run_id,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,...,cpu_model,gpu_count,gpu_model,longitude,latitude,ram_total_size,tracking_mode,on_cloud,pue,model_name
0,2024-08-05T11:52:32,llama3_1_70b-arena-hard-v0.1-8gpus,845ed7f7-e6df-420b-b0f6-74c463c5f85a,1867.868346,0.347547,0.000186,42.5,577.583519,273.079635,0.026902,...,AMD EPYC 7R13 Processor,8,8 x NVIDIA L4,-83.0061,39.9625,728.212360,machine,N,1.22,llama3_1_70b-8gpus
1,2024-08-06T08:09:33,llama3_1_70b_awq_int4-arena-hard-v0.1-8gpus,c92fea3c-ce86-4c7e-8731-c7cd7fb5f115,913.961446,0.150479,0.000165,42.5,577.146518,273.079618,0.013164,...,AMD EPYC 7R13 Processor,8,8 x NVIDIA L4,-83.0061,39.9625,728.212315,machine,N,1.22,llama3_1_70b_awq_int4-8gpus
2,2024-08-06T09:04:39,llama3_1_70b_awq_int4-arena-hard-v0.1-8gpus,895031ee-302e-47d7-99c1-e8e383876f8f,823.504677,0.132878,0.000161,42.5,562.538170,273.079618,0.011861,...,AMD EPYC 7R13 Processor,8,8 x NVIDIA L4,-83.0061,39.9625,728.212315,machine,N,1.22,llama3_1_70b_awq_int4-8gpus
3,2024-08-06T12:57:46,llama3_1_70b_fp8-arena-hard-v0.1-4gpus,cbd8317a-68cf-46a3-8eea-adcb3d9d24f3,1466.116555,0.129593,0.000088,42.5,288.045262,68.162164,0.021116,...,AMD EPYC 7R13 Processor,4,4 x NVIDIA L4,-83.0061,39.9625,181.765770,machine,N,1.22,llama3_1_70b_fp8-4gpus
4,2024-08-06T13:42:14,llama3_1_70b_awq_int4-arena-hard-v0.1-4gpus,f3fd9f2b-b4f8-4d49-bf59-d21af0c60226,828.743464,0.070360,0.000085,42.5,289.168718,68.162164,0.011936,...,AMD EPYC 7R13 Processor,4,4 x NVIDIA L4,-83.0061,39.9625,181.765770,machine,N,1.22,llama3_1_70b_awq_int4-4gpus

In [44]:
# Group by the new model_name and calculate the mean for the selected columns
df_batched = emissions_data_batched.groupby('model_name').agg({
    'duration': 'mean',
    'emissions': 'mean',
    'emissions_rate': 'mean',
    'cpu_power': 'mean',
    'gpu_power': 'mean',
    'ram_power': 'mean',
    'cpu_energy': 'mean',
    'gpu_energy': 'mean',
    'ram_energy': 'mean',
    'energy_consumed': 'mean',
    'gpu_count': 'first'}).reset_index()
    
df_nonbatched = emissions_data_nonbatched.groupby('model_name').agg({
    'duration': 'mean',
    'emissions': 'mean',
    'emissions_rate': 'mean',
    'cpu_power': 'mean',
    'gpu_power': 'mean',
    'ram_power': 'mean',
    'cpu_energy': 'mean',
    'gpu_energy': 'mean',
    'ram_energy': 'mean',
    'energy_consumed': 'mean',
    'gpu_count': 'first'}).reset_index()

In [45]:
df_batched.head(5)

,model_name,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,gpu_energy,ram_energy,energy_consumed,gpu_count
0,llama3_1_70b_awq_int4-4gpus,1480.617988,0.132385,0.000089,42.5,288.748807,68.162162,0.021325,0.143604,0.034161,0.199090,4
1,llama3_1_70b_awq_int4_guided-4gpus,3488.539857,0.214276,0.000069,42.5,200.229282,68.162162,0.050245,0.191476,0.080524,0.322245,4
2,llama3_1_70b_fp8-4gpus,2002.761728,0.179008,0.000089,42.5,288.561002,68.162162,0.028845,0.194161,0.046200,0.269207,4
3,llama3_1_70b_fp8-8gpus,1220.240308,0.211623,0.000173,42.5,581.537797,273.079614,0.017575,0.187966,0.112714,0.318255,8
4,llama3_1_70b_fp8_guided-4gpus,2879.996033,0.251599,0.000087,42.5,288.047993,68.162162,0.041480,0.270455,0.066439,0.378373,4

In [46]:
df_nonbatched.head(5)

,model_name,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,gpu_energy,ram_energy,energy_consumed,gpu_count
0,llama3_1_70b-8gpus,2513.262675,0.471343,0.000187,42.5,563.751591,273.079628,0.036198,0.440552,0.232091,0.708841,8
1,llama3_1_70b_awq_int4-4gpus,828.743464,0.070360,0.000085,42.5,289.168718,68.162164,0.011936,0.074753,0.019123,0.105812,4
2,llama3_1_70b_awq_int4-8gpus,890.192632,0.146427,0.000164,42.5,573.461085,273.079615,0.012821,0.125151,0.082235,0.220208,8
3,llama3_1_70b_awq_int4-8gpus_guided,1692.569733,0.281111,0.000166,42.5,575.850005,273.079634,0.024378,0.242026,0.156352,0.422756,8
4,llama3_1_70b_fp8-4gpus,1466.116555,0.129593,0.000088,42.5,288.045262,68.162164,0.021116,0.139951,0.033825,0.194892,4

In [47]:
df = pd.concat([df_batched, df_nonbatched], ignore_index=True)
df = df.groupby('model_name').agg({
    'duration': 'mean',
    'emissions': 'mean',
    'emissions_rate': 'mean',
    'cpu_power': 'mean',
    'gpu_power': 'mean',
    'ram_power': 'mean',
    'cpu_energy': 'mean',
    'gpu_energy': 'mean',
    'ram_energy': 'mean',
    'energy_consumed': 'mean',
    'gpu_count': 'first'}).reset_index()
df.head(10)

,model_name,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,gpu_energy,ram_energy,energy_consumed,gpu_count
0,llama3_1_70b-8gpus,2513.262675,0.471343,0.000187,42.5,563.751591,273.079628,0.036198,0.440552,0.232091,0.708841,8
1,llama3_1_70b_awq_int4-4gpus,1154.680726,0.101372,0.000087,42.5,288.958763,68.162163,0.016631,0.109179,0.026642,0.152451,4
2,llama3_1_70b_awq_int4-8gpus,890.192632,0.146427,0.000164,42.5,573.461085,273.079615,0.012821,0.125151,0.082235,0.220208,8
3,llama3_1_70b_awq_int4-8gpus_guided,1692.569733,0.281111,0.000166,42.5,575.850005,273.079634,0.024378,0.242026,0.156352,0.422756,8
4,llama3_1_70b_awq_int4_guided-4gpus,3488.539857,0.214276,0.000069,42.5,200.229282,68.162162,0.050245,0.191476,0.080524,0.322245,4
5,llama3_1_70b_fp8-4gpus,1734.439142,0.154301,0.000089,42.5,288.303132,68.162163,0.024981,0.167056,0.040013,0.232050,4
6,llama3_1_70b_fp8-8gpus,1220.240308,0.211623,0.000173,42.5,581.537797,273.079614,0.017575,0.187966,0.112714,0.318255,8
7,llama3_1_70b_fp8_guided-4gpus,2879.996033,0.251599,0.000087,42.5,288.047993,68.162162,0.041480,0.270455,0.066439,0.378373,4
8,llama3_1_70b_fp8_guided-8gpus,1882.436985,0.321359,0.000171,42.5,579.537203,273.079614,0.027112,0.282304,0.173868,0.483285,8
9,llama3_1_8b-4gpus,406.711346,0.031154,0.000077,42.5,290.192641,68.162162,0.005858,0.031608,0.009385,0.046852,4

In [48]:
df['model_id'] = df['model_name']
df['model_name'] = df['model_name'].apply(lambda x: re.sub(r'-\d+gpus', '', x))

In [49]:
df

,model_name,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,gpu_energy,ram_energy,energy_consumed,gpu_count,model_id
0,llama3_1_70b,2513.262675,0.471343,0.000187,42.5,563.751591,273.079628,0.036198,0.440552,0.232091,0.708841,8,llama3_1_70b-8gpus
1,llama3_1_70b_awq_int4,1154.680726,0.101372,0.000087,42.5,288.958763,68.162163,0.016631,0.109179,0.026642,0.152451,4,llama3_1_70b_awq_int4-4gpus
2,llama3_1_70b_awq_int4,890.192632,0.146427,0.000164,42.5,573.461085,273.079615,0.012821,0.125151,0.082235,0.220208,8,llama3_1_70b_awq_int4-8gpus
3,llama3_1_70b_awq_int4_guided,1692.569733,0.281111,0.000166,42.5,575.850005,273.079634,0.024378,0.242026,0.156352,0.422756,8,llama3_1_70b_awq_int4-8gpus_guided
4,llama3_1_70b_awq_int4_guided,3488.539857,0.214276,0.000069,42.5,200.229282,68.162162,0.050245,0.191476,0.080524,0.322245,4,llama3_1_70b_awq_int4_guided-4gpus
5,llama3_1_70b_fp8,1734.439142,0.154301,0.000089,42.5,288.303132,68.162163,0.024981,0.167056,0.040013,0.232050,4,llama3_1_70b_fp8-4gpus
6,llama3_1_70b_fp8,1220.240308,0.211623,0.000173,42.5,581.537797,273.079614,0.017575,0.187966,0.112714,0.318255,8,llama3_1_70b_fp8-8gpus
7,llama3_1_70b_fp8_guided,2879.996033,0.251599,0.000087,42.5,288.047993,68.162162,0.041480,0.270455,0.066439,0.378373,4,llama3_1_70b_fp8_guided-4gpus
8,llama3_1_70b_fp8_guided,1882.436985,0.321359,0.000171,42.5,579.537203,273.079614,0.027112,0.282304,0.173868,0.483285,8,llama3_1_70b_fp8_guided-8gpus
9,llama3_1_8b,406.711346,0.031154,0.000077,42.5,290.192641,68.162162,0.005858,0.031608,0.009385,0.046852,4,llama3_1_8b-4gpus
10,llama3_1_8b_fp8,341.294352,0.025867,0.000076,42.5,275.763867,68.162159,0.004916,0.026110,0.007876,0.038901,4,llama3_1_8b_fp8-4gpus
11,llama3_1_8b_guided,669.515852,0.053497,0.000080,42.5,290.152320,68.162162,0.009643,0.055361,0.015449,0.080452,4,llama3_1_8b_guided-4gpus
12,llama3_70b,1519.788450,0.283470,0.000187,42.5,576.760477,273.079609,0.021889,0.264062,0.140352,0.426303,8,llama3_70b-8gpus
13,llama3_70b_guided,2963.909088,0.554097,0.000187,42.5,578.761208,273.079634,0.042688,0.516876,0.273729,0.833293,8,llama3_70b-8gpus_guided
14,llama3_70b_awq_int4,811.387838,0.132349,0.000163,42.5,592.132110,273.079609,0.011686,0.112394,0.074956,0.199036,8,llama3_70b_awq_int4-8gpus
15,llama3_70b_fp8,871.537337,0.143975,0.000165,42.5,575.377740,273.079609,0.012553,0.123465,0.080503,0.216521,8,llama3_70b_fp8-8gpus
16,llama3_8b,283.092776,0.021880,0.000077,42.5,288.211588,68.162159,0.004077,0.022296,0.006532,0.032905,4,llama3_8b-4gpus
17,llama3_8b_guided,529.400023,0.042992,0.000081,42.5,288.900793,68.162159,0.007625,0.044814,0.012216,0.064655,4,llama3_8b_guided-4gpus
18,mistral_nemo,453.990921,0.037947,0.000084,42.5,288.566338,68.162164,0.006539,0.040054,0.010475,0.057068,4,mistral_nemo-4gpus
19,mistral_nemo_fp8,352.530645,0.027009,0.000077,42.5,285.410582,68.162164,0.005077,0.027405,0.008135,0.040618,4,mistral_nemo_fp8-4gpus
20,mistral_nemo_fp8_guided,712.147651,0.055511,0.000078,42.5,329.127108,68.162164,0.010257,0.056792,0.016433,0.083482,4,mistral_nemo_fp8_guided-4gpus
21,mistral_nemo_guided,684.076005,0.057035,0.000083,42.5,288.828071,68.162164,0.009853,0.060137,0.015784,0.085773,4,mistral_nemo_guided-4gpus

In [50]:
# Perform an outer join to include all models from both DataFrames
df = pd.merge(df, leaderboard_df, on='model_name', how='outer')

# Extract models that have no energy data (all columns from the original df will be NaN)
models_with_no_energy_data = df[df['duration'].isna()]['model_name'].unique()

# Extract models that have no arena score data (all columns from the leaderboard_df will be NaN)
models_with_no_arena_score = df[df['arena_score'].isna()]['model_name'].unique()

df['model_id'] = df['model_id'].fillna(df['model_name'])

df.head(10)

,model_name,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,gpu_energy,ram_energy,...,gpu_count,model_id,arena_score,95_conf_minus,95_conf_plus,CI,output_tok,date,CI_lower,CI_upper
0,gpt-4-0314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,gpt-4-0314,50.00,50.00,50.00,"(-0.00, +0.00)",423.0,2024-08-17,-0.00,0.00
1,gpt-4o,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,gpt-4o,88.09,86.60,89.44,"(-1.49, +1.35)",696.0,2024-08-17,-1.49,1.35
2,gpt-4o-2024-08-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,gpt-4o-2024-08-06,86.55,85.08,88.10,"(-1.47, +1.55)",616.0,2024-08-17,-1.47,1.55
3,gpt-4o-2024-08-06_guided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,gpt-4o-2024-08-06_guided,87.75,86.27,89.18,"(-1.48, +1.43)",625.0,2024-08-17,-1.48,1.43
4,gpt-4o-mini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,gpt-4o-mini,80.09,78.17,81.92,"(-1.92, +1.83)",631.0,2024-08-17,-1.92,1.83
5,gpt-4o-mini_guided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,gpt-4o-mini_guided,86.27,84.67,87.86,"(-1.60, +1.59)",678.0,2024-08-17,-1.60,1.59
6,llama3_1_405b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,llama3_1_405b,72.20,69.91,73.99,"(-2.29, +1.79)",662.0,2024-08-17,-2.29,1.79
7,llama3_1_405b_guided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,llama3_1_405b_guided,79.47,77.49,81.40,"(-1.98, +1.93)",649.0,2024-08-17,-1.98,1.93
8,llama3_1_70b,2513.262675,0.471343,0.000187,42.5,563.751591,273.079628,0.036198,0.440552,0.232091,...,8.0,llama3_1_70b-8gpus,68.05,65.91,70.15,"(-2.14, +2.10)",681.0,2024-08-17,-2.14,2.10
9,llama3_1_70b_awq_int4,1154.680726,0.101372,0.000087,42.5,288.958763,68.162163,0.016631,0.109179,0.026642,...,4.0,llama3_1_70b_awq_int4-4gpus,63.82,61.24,66.03,"(-2.58, +2.21)",641.0,2024-08-17,-2.58,2.21

In [51]:
no_energy = pd.DataFrame({"no energy data": models_with_no_energy_data})
no_energy

              no energy data
0                 gpt-4-0314
1                     gpt-4o
2          gpt-4o-2024-08-06
3   gpt-4o-2024-08-06_guided
4                gpt-4o-mini
5         gpt-4o-mini_guided
6              llama3_1_405b
7       llama3_1_405b_guided
8        llama3_1_70b_guided
9            mistral_large_2
10    mistral_large_2_guided

In [52]:
no_arena = pd.DataFrame({"no arena score": models_with_no_arena_score})
no_arena

        no arena score
0      llama3_1_8b_fp8
1           llama3_70b
2  llama3_70b_awq_int4
3            llama3_8b
4     llama3_8b_guided

In [53]:
# Create the guided column
df['guided'] = df['model_name'].apply(lambda x: 1 if '_guided' in x else 0)

# Strip "_guided" from the model name
df['model_name'] = df['model_name'].apply(lambda x: re.sub(r'_guided', '', x))

In [54]:
df.head(5)

,model_name,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,gpu_energy,ram_energy,...,model_id,arena_score,95_conf_minus,95_conf_plus,CI,output_tok,date,CI_lower,CI_upper,guided
0,gpt-4-0314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,gpt-4-0314,50.00,50.00,50.00,"(-0.00, +0.00)",423.0,2024-08-17,-0.00,0.00,0
1,gpt-4o,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,gpt-4o,88.09,86.60,89.44,"(-1.49, +1.35)",696.0,2024-08-17,-1.49,1.35,0
2,gpt-4o-2024-08-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,gpt-4o-2024-08-06,86.55,85.08,88.10,"(-1.47, +1.55)",616.0,2024-08-17,-1.47,1.55,0
3,gpt-4o-2024-08-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,gpt-4o-2024-08-06_guided,87.75,86.27,89.18,"(-1.48, +1.43)",625.0,2024-08-17,-1.48,1.43,1
4,gpt-4o-mini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,gpt-4o-mini,80.09,78.17,81.92,"(-1.92, +1.83)",631.0,2024-08-17,-1.92,1.83,0

In [55]:
# Add a new column 'quantization' based on the suffixes in the model name
def assign_quantization(model_name):
    if '_fp8' in model_name:
        return 'fp8'
    elif '_awq_int4' in model_name:
        return 'awq_int4'
    else:
        return 'bf16'

In [56]:
df['quantization'] = df['model_name'].apply(assign_quantization)

# Strip the quantization suffixes from the model name
df['model_name'] = df['model_name'].apply(lambda x: re.sub(r'_fp8|_awq_int4', '', x))

In [57]:
df.head(10)

,model_name,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,gpu_energy,ram_energy,...,arena_score,95_conf_minus,95_conf_plus,CI,output_tok,date,CI_lower,CI_upper,guided,quantization
0,gpt-4-0314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,50.00,50.00,50.00,"(-0.00, +0.00)",423.0,2024-08-17,-0.00,0.00,0,bf16
1,gpt-4o,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,88.09,86.60,89.44,"(-1.49, +1.35)",696.0,2024-08-17,-1.49,1.35,0,bf16
2,gpt-4o-2024-08-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,86.55,85.08,88.10,"(-1.47, +1.55)",616.0,2024-08-17,-1.47,1.55,0,bf16
3,gpt-4o-2024-08-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,87.75,86.27,89.18,"(-1.48, +1.43)",625.0,2024-08-17,-1.48,1.43,1,bf16
4,gpt-4o-mini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,80.09,78.17,81.92,"(-1.92, +1.83)",631.0,2024-08-17,-1.92,1.83,0,bf16
5,gpt-4o-mini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,86.27,84.67,87.86,"(-1.60, +1.59)",678.0,2024-08-17,-1.60,1.59,1,bf16
6,llama3_1_405b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,72.20,69.91,73.99,"(-2.29, +1.79)",662.0,2024-08-17,-2.29,1.79,0,bf16
7,llama3_1_405b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,79.47,77.49,81.40,"(-1.98, +1.93)",649.0,2024-08-17,-1.98,1.93,1,bf16
8,llama3_1_70b,2513.262675,0.471343,0.000187,42.5,563.751591,273.079628,0.036198,0.440552,0.232091,...,68.05,65.91,70.15,"(-2.14, +2.10)",681.0,2024-08-17,-2.14,2.10,0,bf16
9,llama3_1_70b,1154.680726,0.101372,0.000087,42.5,288.958763,68.162163,0.016631,0.109179,0.026642,...,63.82,61.24,66.03,"(-2.58, +2.21)",641.0,2024-08-17,-2.58,2.21,0,awq_int4

In [58]:
# Function to extract model class and remove the suffix from the model name
def extract_param_size(model_name):
    match = re.search(r'_\d+b', model_name)
    if match:
        param_size = match.group(0).lstrip('_')
        param_size = param_size.rstrip('b')
        return int(param_size)
    elif model_name == 'mistral_nemo':
        return 12
    elif model_name == 'mistral_large_2':
        return 123
    return np.nan

In [59]:
df['param_size'] = df['model_name'].apply(extract_param_size)
df['model_class'] = df['model_name'].apply(lambda x: re.sub(r'_\d+b', '', x))

df

,model_name,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,gpu_energy,ram_energy,...,95_conf_plus,CI,output_tok,date,CI_lower,CI_upper,guided,quantization,param_size,model_class
0,gpt-4-0314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,50.00,"(-0.00, +0.00)",423.0,2024-08-17,-0.00,0.00,0,bf16,NaN,gpt-4-0314
1,gpt-4o,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,89.44,"(-1.49, +1.35)",696.0,2024-08-17,-1.49,1.35,0,bf16,NaN,gpt-4o
2,gpt-4o-2024-08-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,88.10,"(-1.47, +1.55)",616.0,2024-08-17,-1.47,1.55,0,bf16,NaN,gpt-4o-2024-08-06
3,gpt-4o-2024-08-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,89.18,"(-1.48, +1.43)",625.0,2024-08-17,-1.48,1.43,1,bf16,NaN,gpt-4o-2024-08-06
4,gpt-4o-mini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,81.92,"(-1.92, +1.83)",631.0,2024-08-17,-1.92,1.83,0,bf16,NaN,gpt-4o-mini
5,gpt-4o-mini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,87.86,"(-1.60, +1.59)",678.0,2024-08-17,-1.60,1.59,1,bf16,NaN,gpt-4o-mini
6,llama3_1_405b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,73.99,"(-2.29, +1.79)",662.0,2024-08-17,-2.29,1.79,0,bf16,405.0,llama3_1
7,llama3_1_405b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,81.40,"(-1.98, +1.93)",649.0,2024-08-17,-1.98,1.93,1,bf16,405.0,llama3_1
8,llama3_1_70b,2513.262675,0.471343,0.000187,42.5,563.751591,273.079628,0.036198,0.440552,0.232091,...,70.15,"(-2.14, +2.10)",681.0,2024-08-17,-2.14,2.10,0,bf16,70.0,llama3_1
9,llama3_1_70b,1154.680726,0.101372,0.000087,42.5,288.958763,68.162163,0.016631,0.109179,0.026642,...,66.03,"(-2.58, +2.21)",641.0,2024-08-17,-2.58,2.21,0,awq_int4,70.0,llama3_1
10,llama3_1_70b,890.192632,0.146427,0.000164,42.5,573.461085,273.079615,0.012821,0.125151,0.082235,...,66.03,"(-2.58, +2.21)",641.0,2024-08-17,-2.58,2.21,0,awq_int4,70.0,llama3_1
11,llama3_1_70b,1692.569733,0.281111,0.000166,42.5,575.850005,273.079634,0.024378,0.242026,0.156352,...,76.32,"(-2.08, +2.15)",640.0,2024-08-17,-2.08,2.15,1,awq_int4,70.0,llama3_1
12,llama3_1_70b,3488.539857,0.214276,0.000069,42.5,200.229282,68.162162,0.050245,0.191476,0.080524,...,76.32,"(-2.08, +2.15)",640.0,2024-08-17,-2.08,2.15,1,awq_int4,70.0,llama3_1
13,llama3_1_70b,1734.439142,0.154301,0.000089,42.5,288.303132,68.162163,0.024981,0.167056,0.040013,...,71.23,"(-2.44, +2.44)",689.0,2024-08-17,-2.44,2.44,0,fp8,70.0,llama3_1
14,llama3_1_70b,1220.240308,0.211623,0.000173,42.5,581.537797,273.079614,0.017575,0.187966,0.112714,...,71.23,"(-2.44, +2.44)",689.0,2024-08-17,-2.44,2.44,0,fp8,70.0,llama3_1
15,llama3_1_70b,2879.996033,0.251599,0.000087,42.5,288.047993,68.162162,0.041480,0.270455,0.066439,...,77.38,"(-2.25, +2.24)",646.0,2024-08-17,-2.25,2.24,1,fp8,70.0,llama3_1
16,llama3_1_70b,1882.436985,0.321359,0.000171,42.5,579.537203,273.079614,0.027112,0.282304,0.173868,...,77.38,"(-2.25, +2.24)",646.0,2024-08-17,-2.25,2.24,1,fp8,70.0,llama3_1
17,llama3_1_70b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,80.12,"(-2.12, +1.83)",646.0,2024-08-17,-2.12,1.83,1,bf16,70.0,llama3_1
18,llama3_1_8b,406.711346,0.031154,0.000077,42.5,290.192641,68.162162,0.005858,0.031608,0.009385,...,28.83,"(-1.96, +2.24)",853.0,2024-08-17,-1.96,2.24,0,bf16,8.0,llama3_1
19,llama3_1_8b,341.294352,0.025867,0.000076,42.5,275.763867,68.162159,0.004916,0.026110,0.007876,...,NaN,NaN,NaN,NaN,NaN,NaN,0,fp8,8.0,llama3_1
20,llama3_1_8b,669.515852,0.053497,0.000080,42.5,290.152320,68.162162,0.009643,0.055361,0.015449,...,63.35,"(-2.53, +2.45)",719.0,2024-08-17,-2.53,2.45,1,bf16,8.0,llama3_1
21,llama3_70b,1519.788450,0.283470,0.000187,42.5,576.760477,273.079609,0.021889,0.264062,0.140352,...,NaN,NaN,NaN,NaN,NaN,NaN,0,bf16,70.0,llama3
22,llama3_70b,811.387838,0.132349,0.000163,42.5,592.132110,273.079609,0.011686,0.112394,0.074956,...,NaN,NaN,NaN,NaN,NaN,NaN,0,awq_int4,70.0,llama3
23,llama3_70b,871.537337,0.143975,0.000165,42.5,575.377740,273.079609,0.012553,0.123465,0.080503,...,61.86,"(-2.40, +2.27)",614.0,2024-08-17,-2.40,2.27,0,fp8,70.0,llama3
24,llama3_70b,2963.909088,0.554097,0.000187,42.5,578.761208,273.079634,0.042688,0.516876,0.273729,...,74.53,"(-1.99, +2.19)",583.0,2024-08-17,-1.99,2.19,1,bf16,70.0,llama3
25,llama3_8b,283.092776,0.021880,0.000077,42.5,288.211588,68.162159,0.004077,0.022296,0.006532,...,NaN,NaN,NaN,NaN,NaN,NaN,0,bf16,8.0,llama3
26,llama3_8b,529.400023,0.042992,0.000081,42.5,288.900793,68.162159,0.007625,0.044814,0.012216,...,NaN,NaN,NaN,NaN,NaN,NaN,1,bf16,8.0,llama3
27,mistral_large_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,82.60,"(-2.02, +1.64)",684.0,2024-08-17,-2.02,1.64,0,bf16,123.0,mistral_large_2
28,mistral_large_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,85.41,"(-1.74, +1.78)",777.0,2024-08-17,-1.74,1.78,1,bf16,123.0,mistral_large_2
29,mistral_nemo,453.990921,0.037947,0.000084,42.5,288.566338,68.162164,0.006539,0.040054,0.010475,...,47.46,"(-2.56, +2.56)",541.0,2024-08-17,-2.56,2.56,0,bf16,12.0,mistral_nemo
30,mistral_nemo,352.530645,0.027009,0.000077,42.5,285.410582,68.162164,0.005077,0.027405,0.008135,...,45.36,"(-2.67, +2.63)",552.0,2024-08-17,-2.67,2.63,0,fp8,12.0,mistral_nemo
31,mistral_nemo,712.147651,0.055511,0.000078,42.5,329.127108,68.162164,0.010257,0.056792,0.016433,...,72.25,"(-2.27, +2.24)",633.0,2024-08-17,-2.27,2.24,1,fp8,12.0,mistral_nemo
32,mistral_nemo,684.076005,0.057035,0.000083,42.5,288.828071,68.162164,0.009853,0.060137,0.015784,...,71.57,"(-2.37, +1.97)",613.0,2024-08-17,-2.37,1.97,1,bf16,12.0,mistral_nemo

In [60]:
def map_input_tok(row):
    if row['guided'] == 1:
        return input_tok_map_guided.get(row['model_class'], 0)
    else:
        return input_tok_map.get(row['model_class'], 0)

In [61]:
df['input_tok'] = df.apply(map_input_tok, axis=1)

In [62]:
df['duration_minutes'] = df['duration'] / 60
df

,model_name,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,gpu_energy,ram_energy,...,output_tok,date,CI_lower,CI_upper,guided,quantization,param_size,model_class,input_tok,duration_minutes
0,gpt-4-0314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,423.0,2024-08-17,-0.00,0.00,0,bf16,NaN,gpt-4-0314,0.000,NaN
1,gpt-4o,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,696.0,2024-08-17,-1.49,1.35,0,bf16,NaN,gpt-4o,0.000,NaN
2,gpt-4o-2024-08-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,616.0,2024-08-17,-1.47,1.55,0,bf16,NaN,gpt-4o-2024-08-06,0.000,NaN
3,gpt-4o-2024-08-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,625.0,2024-08-17,-1.48,1.43,1,bf16,NaN,gpt-4o-2024-08-06,0.000,NaN
4,gpt-4o-mini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,631.0,2024-08-17,-1.92,1.83,0,bf16,NaN,gpt-4o-mini,0.000,NaN
5,gpt-4o-mini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,678.0,2024-08-17,-1.60,1.59,1,bf16,NaN,gpt-4o-mini,0.000,NaN
6,llama3_1_405b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,662.0,2024-08-17,-2.29,1.79,0,bf16,405.0,llama3_1,135.142,NaN
7,llama3_1_405b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,649.0,2024-08-17,-1.98,1.93,1,bf16,405.0,llama3_1,874.592,NaN
8,llama3_1_70b,2513.262675,0.471343,0.000187,42.5,563.751591,273.079628,0.036198,0.440552,0.232091,...,681.0,2024-08-17,-2.14,2.10,0,bf16,70.0,llama3_1,135.142,41.887711
9,llama3_1_70b,1154.680726,0.101372,0.000087,42.5,288.958763,68.162163,0.016631,0.109179,0.026642,...,641.0,2024-08-17,-2.58,2.21,0,awq_int4,70.0,llama3_1,135.142,19.244679
10,llama3_1_70b,890.192632,0.146427,0.000164,42.5,573.461085,273.079615,0.012821,0.125151,0.082235,...,641.0,2024-08-17,-2.58,2.21,0,awq_int4,70.0,llama3_1,135.142,14.836544
11,llama3_1_70b,1692.569733,0.281111,0.000166,42.5,575.850005,273.079634,0.024378,0.242026,0.156352,...,640.0,2024-08-17,-2.08,2.15,1,awq_int4,70.0,llama3_1,874.592,28.209496
12,llama3_1_70b,3488.539857,0.214276,0.000069,42.5,200.229282,68.162162,0.050245,0.191476,0.080524,...,640.0,2024-08-17,-2.08,2.15,1,awq_int4,70.0,llama3_1,874.592,58.142331
13,llama3_1_70b,1734.439142,0.154301,0.000089,42.5,288.303132,68.162163,0.024981,0.167056,0.040013,...,689.0,2024-08-17,-2.44,2.44,0,fp8,70.0,llama3_1,135.142,28.907319
14,llama3_1_70b,1220.240308,0.211623,0.000173,42.5,581.537797,273.079614,0.017575,0.187966,0.112714,...,689.0,2024-08-17,-2.44,2.44,0,fp8,70.0,llama3_1,135.142,20.337338
15,llama3_1_70b,2879.996033,0.251599,0.000087,42.5,288.047993,68.162162,0.041480,0.270455,0.066439,...,646.0,2024-08-17,-2.25,2.24,1,fp8,70.0,llama3_1,874.592,47.999934
16,llama3_1_70b,1882.436985,0.321359,0.000171,42.5,579.537203,273.079614,0.027112,0.282304,0.173868,...,646.0,2024-08-17,-2.25,2.24,1,fp8,70.0,llama3_1,874.592,31.373950
17,llama3_1_70b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,646.0,2024-08-17,-2.12,1.83,1,bf16,70.0,llama3_1,874.592,NaN
18,llama3_1_8b,406.711346,0.031154,0.000077,42.5,290.192641,68.162162,0.005858,0.031608,0.009385,...,853.0,2024-08-17,-1.96,2.24,0,bf16,8.0,llama3_1,135.142,6.778522
19,llama3_1_8b,341.294352,0.025867,0.000076,42.5,275.763867,68.162159,0.004916,0.026110,0.007876,...,NaN,NaN,NaN,NaN,0,fp8,8.0,llama3_1,135.142,5.688239
20,llama3_1_8b,669.515852,0.053497,0.000080,42.5,290.152320,68.162162,0.009643,0.055361,0.015449,...,719.0,2024-08-17,-2.53,2.45,1,bf16,8.0,llama3_1,874.592,11.158598
21,llama3_70b,1519.788450,0.283470,0.000187,42.5,576.760477,273.079609,0.021889,0.264062,0.140352,...,NaN,NaN,NaN,NaN,0,bf16,70.0,llama3,135.142,25.329808
22,llama3_70b,811.387838,0.132349,0.000163,42.5,592.132110,273.079609,0.011686,0.112394,0.074956,...,NaN,NaN,NaN,NaN,0,awq_int4,70.0,llama3,135.142,13.523131
23,llama3_70b,871.537337,0.143975,0.000165,42.5,575.377740,273.079609,0.012553,0.123465,0.080503,...,614.0,2024-08-17,-2.40,2.27,0,fp8,70.0,llama3,135.142,14.525622
24,llama3_70b,2963.909088,0.554097,0.000187,42.5,578.761208,273.079634,0.042688,0.516876,0.273729,...,583.0,2024-08-17,-1.99,2.19,1,bf16,70.0,llama3,874.592,49.398485
25,llama3_8b,283.092776,0.021880,0.000077,42.5,288.211588,68.162159,0.004077,0.022296,0.006532,...,NaN,NaN,NaN,NaN,0,bf16,8.0,llama3,135.142,4.718213
26,llama3_8b,529.400023,0.042992,0.000081,42.5,288.900793,68.162159,0.007625,0.044814,0.012216,...,NaN,NaN,NaN,NaN,1,bf16,8.0,llama3,874.592,8.823334
27,mistral_large_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,684.0,2024-08-17,-2.02,1.64,0,bf16,123.0,mistral_large_2,0.000,NaN
28,mistral_large_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,777.0,2024-08-17,-1.74,1.78,1,bf16,123.0,mistral_large_2,0.000,NaN
29,mistral_nemo,453.990921,0.037947,0.000084,42.5,288.566338,68.162164,0.006539,0.040054,0.010475,...,541.0,2024-08-17,-2.56,2.56,0,bf16,12.0,mistral_nemo,143.190,7.566515
30,mistral_nemo,352.530645,0.027009,0.000077,42.5,285.410582,68.162164,0.005077,0.027405,0.008135,...,552.0,2024-08-17,-2.67,2.63,0,fp8,12.0,mistral_nemo,143.190,5.875511
31,mistral_nemo,712.147651,0.055511,0.000078,42.5,329.127108,68.162164,0.010257,0.056792,0.016433,...,633.0,2024-08-17,-2.27,2.24,1,fp8,12.0,mistral_nemo,921.216,11.869128
32,mistral_nemo,684.076005,0.057035,0.000083,42.5,288.828071,68.162164,0.009853,0.060137,0.015784,...,613.0,2024-08-17,-2.37,1.97,1,bf16,12.0,mistral_nemo,921.216,11.401267

In [63]:
df['num_prompts'] = 500
df['sec_per_prompt'] = df['duration'] / df['num_prompts']
df

,model_name,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,gpu_energy,ram_energy,...,CI_lower,CI_upper,guided,quantization,param_size,model_class,input_tok,duration_minutes,num_prompts,sec_per_prompt
0,gpt-4-0314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.00,0.00,0,bf16,NaN,gpt-4-0314,0.000,NaN,500,NaN
1,gpt-4o,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.49,1.35,0,bf16,NaN,gpt-4o,0.000,NaN,500,NaN
2,gpt-4o-2024-08-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.47,1.55,0,bf16,NaN,gpt-4o-2024-08-06,0.000,NaN,500,NaN
3,gpt-4o-2024-08-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.48,1.43,1,bf16,NaN,gpt-4o-2024-08-06,0.000,NaN,500,NaN
4,gpt-4o-mini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.92,1.83,0,bf16,NaN,gpt-4o-mini,0.000,NaN,500,NaN
5,gpt-4o-mini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.60,1.59,1,bf16,NaN,gpt-4o-mini,0.000,NaN,500,NaN
6,llama3_1_405b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-2.29,1.79,0,bf16,405.0,llama3_1,135.142,NaN,500,NaN
7,llama3_1_405b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.98,1.93,1,bf16,405.0,llama3_1,874.592,NaN,500,NaN
8,llama3_1_70b,2513.262675,0.471343,0.000187,42.5,563.751591,273.079628,0.036198,0.440552,0.232091,...,-2.14,2.10,0,bf16,70.0,llama3_1,135.142,41.887711,500,5.026525
9,llama3_1_70b,1154.680726,0.101372,0.000087,42.5,288.958763,68.162163,0.016631,0.109179,0.026642,...,-2.58,2.21,0,awq_int4,70.0,llama3_1,135.142,19.244679,500,2.309361
10,llama3_1_70b,890.192632,0.146427,0.000164,42.5,573.461085,273.079615,0.012821,0.125151,0.082235,...,-2.58,2.21,0,awq_int4,70.0,llama3_1,135.142,14.836544,500,1.780385
11,llama3_1_70b,1692.569733,0.281111,0.000166,42.5,575.850005,273.079634,0.024378,0.242026,0.156352,...,-2.08,2.15,1,awq_int4,70.0,llama3_1,874.592,28.209496,500,3.385139
12,llama3_1_70b,3488.539857,0.214276,0.000069,42.5,200.229282,68.162162,0.050245,0.191476,0.080524,...,-2.08,2.15,1,awq_int4,70.0,llama3_1,874.592,58.142331,500,6.977080
13,llama3_1_70b,1734.439142,0.154301,0.000089,42.5,288.303132,68.162163,0.024981,0.167056,0.040013,...,-2.44,2.44,0,fp8,70.0,llama3_1,135.142,28.907319,500,3.468878
14,llama3_1_70b,1220.240308,0.211623,0.000173,42.5,581.537797,273.079614,0.017575,0.187966,0.112714,...,-2.44,2.44,0,fp8,70.0,llama3_1,135.142,20.337338,500,2.440481
15,llama3_1_70b,2879.996033,0.251599,0.000087,42.5,288.047993,68.162162,0.041480,0.270455,0.066439,...,-2.25,2.24,1,fp8,70.0,llama3_1,874.592,47.999934,500,5.759992
16,llama3_1_70b,1882.436985,0.321359,0.000171,42.5,579.537203,273.079614,0.027112,0.282304,0.173868,...,-2.25,2.24,1,fp8,70.0,llama3_1,874.592,31.373950,500,3.764874
17,llama3_1_70b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-2.12,1.83,1,bf16,70.0,llama3_1,874.592,NaN,500,NaN
18,llama3_1_8b,406.711346,0.031154,0.000077,42.5,290.192641,68.162162,0.005858,0.031608,0.009385,...,-1.96,2.24,0,bf16,8.0,llama3_1,135.142,6.778522,500,0.813423
19,llama3_1_8b,341.294352,0.025867,0.000076,42.5,275.763867,68.162159,0.004916,0.026110,0.007876,...,NaN,NaN,0,fp8,8.0,llama3_1,135.142,5.688239,500,0.682589
20,llama3_1_8b,669.515852,0.053497,0.000080,42.5,290.152320,68.162162,0.009643,0.055361,0.015449,...,-2.53,2.45,1,bf16,8.0,llama3_1,874.592,11.158598,500,1.339032
21,llama3_70b,1519.788450,0.283470,0.000187,42.5,576.760477,273.079609,0.021889,0.264062,0.140352,...,NaN,NaN,0,bf16,70.0,llama3,135.142,25.329808,500,3.039577
22,llama3_70b,811.387838,0.132349,0.000163,42.5,592.132110,273.079609,0.011686,0.112394,0.074956,...,NaN,NaN,0,awq_int4,70.0,llama3,135.142,13.523131,500,1.622776
23,llama3_70b,871.537337,0.143975,0.000165,42.5,575.377740,273.079609,0.012553,0.123465,0.080503,...,-2.40,2.27,0,fp8,70.0,llama3,135.142,14.525622,500,1.743075
24,llama3_70b,2963.909088,0.554097,0.000187,42.5,578.761208,273.079634,0.042688,0.516876,0.273729,...,-1.99,2.19,1,bf16,70.0,llama3,874.592,49.398485,500,5.927818
25,llama3_8b,283.092776,0.021880,0.000077,42.5,288.211588,68.162159,0.004077,0.022296,0.006532,...,NaN,NaN,0,bf16,8.0,llama3,135.142,4.718213,500,0.566186
26,llama3_8b,529.400023,0.042992,0.000081,42.5,288.900793,68.162159,0.007625,0.044814,0.012216,...,NaN,NaN,1,bf16,8.0,llama3,874.592,8.823334,500,1.058800
27,mistral_large_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-2.02,1.64,0,bf16,123.0,mistral_large_2,0.000,NaN,500,NaN
28,mistral_large_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.74,1.78,1,bf16,123.0,mistral_large_2,0.000,NaN,500,NaN
29,mistral_nemo,453.990921,0.037947,0.000084,42.5,288.566338,68.162164,0.006539,0.040054,0.010475,...,-2.56,2.56,0,bf16,12.0,mistral_nemo,143.190,7.566515,500,0.907982
30,mistral_nemo,352.530645,0.027009,0.000077,42.5,285.410582,68.162164,0.005077,0.027405,0.008135,...,-2.67,2.63,0,fp8,12.0,mistral_nemo,143.190,5.875511,500,0.705061
31,mistral_nemo,712.147651,0.055511,0.000078,42.5,329.127108,68.162164,0.010257,0.056792,0.016433,...,-2.27,2.24,1,fp8,12.0,mistral_nemo,921.216,11.869128,500,1.424295
32,mistral_nemo,684.076005,0.057035,0.000083,42.5,288.828071,68.162164,0.009853,0.060137,0.015784,...,-2.37,1.97,1,bf16,12.0,mistral_nemo,921.216,11.401267,500,1.368152

In [64]:
df.dtypes

model_name           object
duration            float64
emissions           float64
emissions_rate      float64
cpu_power           float64
gpu_power           float64
ram_power           float64
cpu_energy          float64
gpu_energy          float64
ram_energy          float64
energy_consumed     float64
gpu_count           float64
model_id             object
arena_score         float64
95_conf_minus       float64
95_conf_plus        float64
CI                   object
output_tok          float64
date                 object
CI_lower            float64
CI_upper            float64
guided                int64
quantization         object
param_size          float64
model_class          object
input_tok           float64
duration_minutes    float64
num_prompts           int64
sec_per_prompt      float64
dtype: object

In [65]:
new_column_order = [
    'model_id',
    'model_name',
    'model_class',        
    'param_size', 
    'gpu_count',        
    'quantization',       
    'guided',             
    'num_prompts',        
    'output_tok',         
    'input_tok',          
    'arena_score',
    'CI', 
    'CI_lower',
    'CI_upper',        
    '95_conf_plus',       
    '95_conf_minus',      
    'duration',
    'duration_minutes',
    'sec_per_prompt',
    'cpu_power',
    'gpu_power',
    'ram_power',
    'cpu_energy',
    'gpu_energy',
    'ram_energy',
    'energy_consumed',     
    'emissions',
    'emissions_rate'
]

df = df[new_column_order]

df

,model_id,model_name,model_class,param_size,gpu_count,quantization,guided,num_prompts,output_tok,input_tok,...,sec_per_prompt,cpu_power,gpu_power,ram_power,cpu_energy,gpu_energy,ram_energy,energy_consumed,emissions,emissions_rate
0,gpt-4-0314,gpt-4-0314,gpt-4-0314,NaN,NaN,bf16,0,500,423.0,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,gpt-4o,gpt-4o,gpt-4o,NaN,NaN,bf16,0,500,696.0,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,gpt-4o-2024-08-06,gpt-4o-2024-08-06,gpt-4o-2024-08-06,NaN,NaN,bf16,0,500,616.0,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,gpt-4o-2024-08-06_guided,gpt-4o-2024-08-06,gpt-4o-2024-08-06,NaN,NaN,bf16,1,500,625.0,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,gpt-4o-mini,gpt-4o-mini,gpt-4o-mini,NaN,NaN,bf16,0,500,631.0,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,gpt-4o-mini_guided,gpt-4o-mini,gpt-4o-mini,NaN,NaN,bf16,1,500,678.0,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,llama3_1_405b,llama3_1_405b,llama3_1,405.0,NaN,bf16,0,500,662.0,135.142,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,llama3_1_405b_guided,llama3_1_405b,llama3_1,405.0,NaN,bf16,1,500,649.0,874.592,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,llama3_1_70b-8gpus,llama3_1_70b,llama3_1,70.0,8.0,bf16,0,500,681.0,135.142,...,5.026525,42.5,563.751591,273.079628,0.036198,0.440552,0.232091,0.708841,0.471343,0.000187
9,llama3_1_70b_awq_int4-4gpus,llama3_1_70b,llama3_1,70.0,4.0,awq_int4,0,500,641.0,135.142,...,2.309361,42.5,288.958763,68.162163,0.016631,0.109179,0.026642,0.152451,0.101372,0.000087
10,llama3_1_70b_awq_int4-8gpus,llama3_1_70b,llama3_1,70.0,8.0,awq_int4,0,500,641.0,135.142,...,1.780385,42.5,573.461085,273.079615,0.012821,0.125151,0.082235,0.220208,0.146427,0.000164
11,llama3_1_70b_awq_int4-8gpus_guided,llama3_1_70b,llama3_1,70.0,8.0,awq_int4,1,500,640.0,874.592,...,3.385139,42.5,575.850005,273.079634,0.024378,0.242026,0.156352,0.422756,0.281111,0.000166
12,llama3_1_70b_awq_int4_guided-4gpus,llama3_1_70b,llama3_1,70.0,4.0,awq_int4,1,500,640.0,874.592,...,6.977080,42.5,200.229282,68.162162,0.050245,0.191476,0.080524,0.322245,0.214276,0.000069
13,llama3_1_70b_fp8-4gpus,llama3_1_70b,llama3_1,70.0,4.0,fp8,0,500,689.0,135.142,...,3.468878,42.5,288.303132,68.162163,0.024981,0.167056,0.040013,0.232050,0.154301,0.000089
14,llama3_1_70b_fp8-8gpus,llama3_1_70b,llama3_1,70.0,8.0,fp8,0,500,689.0,135.142,...,2.440481,42.5,581.537797,273.079614,0.017575,0.187966,0.112714,0.318255,0.211623,0.000173
15,llama3_1_70b_fp8_guided-4gpus,llama3_1_70b,llama3_1,70.0,4.0,fp8,1,500,646.0,874.592,...,5.759992,42.5,288.047993,68.162162,0.041480,0.270455,0.066439,0.378373,0.251599,0.000087
16,llama3_1_70b_fp8_guided-8gpus,llama3_1_70b,llama3_1,70.0,8.0,fp8,1,500,646.0,874.592,...,3.764874,42.5,579.537203,273.079614,0.027112,0.282304,0.173868,0.483285,0.321359,0.000171
17,llama3_1_70b_guided,llama3_1_70b,llama3_1,70.0,NaN,bf16,1,500,646.0,874.592,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,llama3_1_8b-4gpus,llama3_1_8b,llama3_1,8.0,4.0,bf16,0,500,853.0,135.142,...,0.813423,42.5,290.192641,68.162162,0.005858,0.031608,0.009385,0.046852,0.031154,0.000077
19,llama3_1_8b_fp8-4gpus,llama3_1_8b,llama3_1,8.0,4.0,fp8,0,500,NaN,135.142,...,0.682589,42.5,275.763867,68.162159,0.004916,0.026110,0.007876,0.038901,0.025867,0.000076
20,llama3_1_8b_guided-4gpus,llama3_1_8b,llama3_1,8.0,4.0,bf16,1,500,719.0,874.592,...,1.339032,42.5,290.152320,68.162162,0.009643,0.055361,0.015449,0.080452,0.053497,0.000080
21,llama3_70b-8gpus,llama3_70b,llama3,70.0,8.0,bf16,0,500,NaN,135.142,...,3.039577,42.5,576.760477,273.079609,0.021889,0.264062,0.140352,0.426303,0.283470,0.000187
22,llama3_70b_awq_int4-8gpus,llama3_70b,llama3,70.0,8.0,awq_int4,0,500,NaN,135.142,...,1.622776,42.5,592.132110,273.079609,0.011686,0.112394,0.074956,0.199036,0.132349,0.000163
23,llama3_70b_fp8-8gpus,llama3_70b,llama3,70.0,8.0,fp8,0,500,614.0,135.142,...,1.743075,42.5,575.377740,273.079609,0.012553,0.123465,0.080503,0.216521,0.143975,0.000165
24,llama3_70b-8gpus_guided,llama3_70b,llama3,70.0,8.0,bf16,1,500,583.0,874.592,...,5.927818,42.5,578.761208,273.079634,0.042688,0.516876,0.273729,0.833293,0.554097,0.000187
25,llama3_8b-4gpus,llama3_8b,llama3,8.0,4.0,bf16,0,500,NaN,135.142,...,0.566186,42.5,288.211588,68.162159,0.004077,0.022296,0.006532,0.032905,0.021880,0.000077
26,llama3_8b_guided-4gpus,llama3_8b,llama3,8.0,4.0,bf16,1,500,NaN,874.592,...,1.058800,42.5,288.900793,68.162159,0.007625,0.044814,0.012216,0.064655,0.042992,0.000081
27,mistral_large_2,mistral_large_2,mistral_large_2,123.0,NaN,bf16,0,500,684.0,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,mistral_large_2_guided,mistral_large_2,mistral_large_2,123.0,NaN,bf16,1,500,777.0,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,mistral_nemo-4gpus,mistral_nemo,mistral_nemo,12.0,4.0,bf16,0,500,541.0,143.190,...,0.907982,42.5,288.566338,68.162164,0.006539,0.040054,0.010475,0.057068,0.037947,0.000084
30,mistral_nemo_fp8-4gpus,mistral_nemo,mistral_nemo,12.0,4.0,fp8,0,500,552.0,143.190,...,0.705061,42.5,285.410582,68.162164,0.005077,0.027405,0.008135,0.040618,0.027009,0.000077
31,mistral_nemo_fp8_guided-4gpus,mistral_nemo,mistral_nemo,12.0,4.0,fp8,1,500,633.0,921.216,...,1.424295,42.5,329.127108,68.162164,0.010257,0.056792,0.016433,0.083482,0.055511,0.000078
32,mistral_nemo_guided-4gpus,mistral_nemo,mistral_nemo,12.0,4.0,bf16,1,500,613.0,921.216,...,1.368152,42.5,288.828071,68.162164,0.009853,0.060137,0.015784,0.085773,0.057035,0.000083

In [66]:
# Define the relative path to the target directory
save_path = '../results/data/results.parquet'

# Save the DataFrame to the Parquet file
df.to_parquet(save_path, index=False)